# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3d32c5fcbe33bf5d4caa9969c3f5943482cfe842555363359276a6aebdc5a85f37b432818c7fa8f7c7a76b1f021dd199663a093b225761e75bc076e531afeb9

test:
  secret_key_base: d1c275a3b9c295db01143ebcbc44e406e39c5233b79da0aee4d311b5a942a011686420161efb695fa2fde2058627f73a2df0815d05754298760f66f8b8fb85fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
